name: scripts

packages:
  - . # this includes your current project as a "package"

scripts:
  build:
    run: dart run build_runner build --delete-conflicting-outputs
  watch:
    run: dart run build_runner watch --delete-conflicting-outputs
  clean:
    run: flutter clean
  format:
    run: dart format .
  get:
    run: flutter pub get
  fix:
    run: dart fix --apply
